/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'contact' : string,
  'name' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'address' : string,
  'citizenshipUpload' : File,
  'workArea' : string,
}
export type ExternalBlob = Uint8Array;
export interface File {
  'id' : bigint,
  'content' : ExternalBlob,
  'fileName' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface House {
  'totalFloor' : string,
  'contact' : string,
  'ownerName' : string,
  'builtYear' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'notes' : string,
  'naksaPass' : string,
  'price' : string,
  'totalLandArea' : string,
  'facing' : string,
  'location' : string,
  'attachments' : Array<File>,
  'rooms' : string,
}
export interface OtherProperty {
  'title' : string,
  'contact' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'notes' : string,
  'category' : string,
  'price' : string,
  'location' : string,
  'attachments' : Array<File>,
}
export interface Property {
  'locationUrl' : string,
  'roadInfo' : string,
  'contact' : string,
  'ownerName' : string,
  'propertyType' : string,
  'nagarpalika' : string,
  'mukhSize' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'lambai' : string,
  'address' : string,
  'landArea' : string,
  'notes' : string,
  'price' : string,
  'facing' : string,
  'attachments' : Array<File>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAgent' : ActorMethod<[bigint], undefined>,
  'deleteFile' : ActorMethod<[bigint], undefined>,
  'deleteHouse' : ActorMethod<[bigint], undefined>,
  'deleteOtherProperty' : ActorMethod<[bigint], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'getAgent' : ActorMethod<[bigint], [] | [Agent]>,
  'getAllAgentsSorted' : ActorMethod<[], Array<Agent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[bigint], [] | [File]>,
  'getHouse' : ActorMethod<[bigint], [] | [House]>,
  'getOtherProperty' : ActorMethod<[bigint], [] | [OtherProperty]>,
  'getPropertiesByType' : ActorMethod<[string], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAgent' : ActorMethod<[Agent], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveHouse' : ActorMethod<[House], bigint>,
  'saveOtherProperty' : ActorMethod<[OtherProperty], bigint>,
  'saveProperty' : ActorMethod<[Property], bigint>,
  'updateAgent' : ActorMethod<[bigint, Agent], undefined>,
  'updateHouse' : ActorMethod<[bigint, House], undefined>,
  'updateOtherProperty' : ActorMethod<[bigint, OtherProperty], undefined>,
  'updateProperty' : ActorMethod<[bigint, Property], undefined>,
  'uploadFile' : ActorMethod<[string, ExternalBlob], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];