/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const File = IDL.Record({
  'id' : IDL.Nat,
  'content' : ExternalBlob,
  'fileName' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const Agent = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'address' : IDL.Text,
  'citizenshipUpload' : File,
  'workArea' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const House = IDL.Record({
  'totalFloor' : IDL.Text,
  'contact' : IDL.Text,
  'ownerName' : IDL.Text,
  'builtYear' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'notes' : IDL.Text,
  'naksaPass' : IDL.Text,
  'price' : IDL.Text,
  'totalLandArea' : IDL.Text,
  'facing' : IDL.Text,
  'location' : IDL.Text,
  'attachments' : IDL.Vec(File),
  'rooms' : IDL.Text,
});
export const OtherProperty = IDL.Record({
  'title' : IDL.Text,
  'contact' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'location' : IDL.Text,
  'attachments' : IDL.Vec(File),
});
export const Property = IDL.Record({
  'locationUrl' : IDL.Text,
  'roadInfo' : IDL.Text,
  'contact' : IDL.Text,
  'ownerName' : IDL.Text,
  'propertyType' : IDL.Text,
  'nagarpalika' : IDL.Text,
  'mukhSize' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'lambai' : IDL.Text,
  'address' : IDL.Text,
  'landArea' : IDL.Text,
  'notes' : IDL.Text,
  'price' : IDL.Text,
  'facing' : IDL.Text,
  'attachments' : IDL.Vec(File),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAgent' : IDL.Func([IDL.Nat], [], []),
  'deleteFile' : IDL.Func([IDL.Nat], [], []),
  'deleteHouse' : IDL.Func([IDL.Nat], [], []),
  'deleteOtherProperty' : IDL.Func([IDL.Nat], [], []),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'getAgent' : IDL.Func([IDL.Nat], [IDL.Opt(Agent)], ['query']),
  'getAllAgentsSorted' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([IDL.Nat], [IDL.Opt(File)], ['query']),
  'getHouse' : IDL.Func([IDL.Nat], [IDL.Opt(House)], ['query']),
  'getOtherProperty' : IDL.Func([IDL.Nat], [IDL.Opt(OtherProperty)], ['query']),
  'getPropertiesByType' : IDL.Func([IDL.Text], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAgent' : IDL.Func([Agent], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveHouse' : IDL.Func([House], [IDL.Nat], []),
  'saveOtherProperty' : IDL.Func([OtherProperty], [IDL.Nat], []),
  'saveProperty' : IDL.Func([Property], [IDL.Nat], []),
  'updateAgent' : IDL.Func([IDL.Nat, Agent], [], []),
  'updateHouse' : IDL.Func([IDL.Nat, House], [], []),
  'updateOtherProperty' : IDL.Func([IDL.Nat, OtherProperty], [], []),
  'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
  'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const File = IDL.Record({
    'id' : IDL.Nat,
    'content' : ExternalBlob,
    'fileName' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const Agent = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'address' : IDL.Text,
    'citizenshipUpload' : File,
    'workArea' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const House = IDL.Record({
    'totalFloor' : IDL.Text,
    'contact' : IDL.Text,
    'ownerName' : IDL.Text,
    'builtYear' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'notes' : IDL.Text,
    'naksaPass' : IDL.Text,
    'price' : IDL.Text,
    'totalLandArea' : IDL.Text,
    'facing' : IDL.Text,
    'location' : IDL.Text,
    'attachments' : IDL.Vec(File),
    'rooms' : IDL.Text,
  });
  const OtherProperty = IDL.Record({
    'title' : IDL.Text,
    'contact' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'location' : IDL.Text,
    'attachments' : IDL.Vec(File),
  });
  const Property = IDL.Record({
    'locationUrl' : IDL.Text,
    'roadInfo' : IDL.Text,
    'contact' : IDL.Text,
    'ownerName' : IDL.Text,
    'propertyType' : IDL.Text,
    'nagarpalika' : IDL.Text,
    'mukhSize' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'lambai' : IDL.Text,
    'address' : IDL.Text,
    'landArea' : IDL.Text,
    'notes' : IDL.Text,
    'price' : IDL.Text,
    'facing' : IDL.Text,
    'attachments' : IDL.Vec(File),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAgent' : IDL.Func([IDL.Nat], [], []),
    'deleteFile' : IDL.Func([IDL.Nat], [], []),
    'deleteHouse' : IDL.Func([IDL.Nat], [], []),
    'deleteOtherProperty' : IDL.Func([IDL.Nat], [], []),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'getAgent' : IDL.Func([IDL.Nat], [IDL.Opt(Agent)], ['query']),
    'getAllAgentsSorted' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([IDL.Nat], [IDL.Opt(File)], ['query']),
    'getHouse' : IDL.Func([IDL.Nat], [IDL.Opt(House)], ['query']),
    'getOtherProperty' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(OtherProperty)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAgent' : IDL.Func([Agent], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveHouse' : IDL.Func([House], [IDL.Nat], []),
    'saveOtherProperty' : IDL.Func([OtherProperty], [IDL.Nat], []),
    'saveProperty' : IDL.Func([Property], [IDL.Nat], []),
    'updateAgent' : IDL.Func([IDL.Nat, Agent], [], []),
    'updateHouse' : IDL.Func([IDL.Nat, House], [], []),
    'updateOtherProperty' : IDL.Func([IDL.Nat, OtherProperty], [], []),
    'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
    'uploadFile' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };