/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    locationUrl: string;
    roadInfo: string;
    contact: string;
    ownerName: string;
    propertyType: string;
    nagarpalika: string;
    mukhSize: string;
    createdAt: bigint;
    createdBy: Principal;
    lambai: string;
    address: string;
    landArea: string;
    notes: string;
    price: string;
    facing: string;
    attachments: Array<File>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface File {
    id: bigint;
    content: ExternalBlob;
    fileName: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface Agent {
    contact: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    citizenshipUpload: File;
    workArea: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OtherProperty {
    title: string;
    contact: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    category: string;
    price: string;
    location: string;
    attachments: Array<File>;
}
export interface House {
    totalFloor: string;
    contact: string;
    ownerName: string;
    builtYear: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    naksaPass: string;
    price: string;
    totalLandArea: string;
    facing: string;
    location: string;
    attachments: Array<File>;
    rooms: string;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAgent(id: bigint): Promise<void>;
    deleteFile(id: bigint): Promise<void>;
    deleteHouse(id: bigint): Promise<void>;
    deleteOtherProperty(id: bigint): Promise<void>;
    deleteProperty(id: bigint): Promise<void>;
    getAgent(id: bigint): Promise<Agent | null>;
    getAllAgentsSorted(): Promise<Array<Agent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFile(id: bigint): Promise<File | null>;
    getHouse(id: bigint): Promise<House | null>;
    getOtherProperty(id: bigint): Promise<OtherProperty | null>;
    getPropertiesByType(propertyType: string): Promise<Array<Property>>;
    getProperty(id: bigint): Promise<Property | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveAgent(agent: Agent): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveHouse(house: House): Promise<bigint>;
    saveOtherProperty(otherProperty: OtherProperty): Promise<bigint>;
    saveProperty(property: Property): Promise<bigint>;
    updateAgent(id: bigint, updatedAgent: Agent): Promise<void>;
    updateHouse(id: bigint, updatedHouse: House): Promise<void>;
    updateOtherProperty(id: bigint, updatedProperty: OtherProperty): Promise<void>;
    updateProperty(id: bigint, updatedProperty: Property): Promise<void>;
    uploadFile(fileName: string, content: ExternalBlob): Promise<bigint>;
}
import type { Agent as _Agent, ExternalBlob as _ExternalBlob, File as _File, House as _House, OtherProperty as _OtherProperty, Property as _Property, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgent(arg0);
            return result;
        }
    }
    async deleteFile(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteHouse(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHouse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHouse(arg0);
            return result;
        }
    }
    async deleteOtherProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOtherProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOtherProperty(arg0);
            return result;
        }
    }
    async deleteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async getAgent(arg0: bigint): Promise<Agent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgentsSorted(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgentsSorted();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgentsSorted();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFile(arg0: bigint): Promise<File | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHouse(arg0: bigint): Promise<House | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHouse(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHouse(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOtherProperty(arg0: bigint): Promise<OtherProperty | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOtherProperty(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOtherProperty(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPropertiesByType(arg0: string): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPropertiesByType(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPropertiesByType(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveAgent(arg0: Agent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAgent(await to_candid_Agent_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAgent(await to_candid_Agent_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveHouse(arg0: House): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveHouse(await to_candid_House_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveHouse(await to_candid_House_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveOtherProperty(arg0: OtherProperty): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOtherProperty(await to_candid_OtherProperty_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOtherProperty(await to_candid_OtherProperty_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProperty(arg0: Property): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProperty(await to_candid_Property_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProperty(await to_candid_Property_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAgent(arg0: bigint, arg1: Agent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(arg0, await to_candid_Agent_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(arg0, await to_candid_Agent_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHouse(arg0: bigint, arg1: House): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHouse(arg0, await to_candid_House_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHouse(arg0, await to_candid_House_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOtherProperty(arg0: bigint, arg1: OtherProperty): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOtherProperty(arg0, await to_candid_OtherProperty_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOtherProperty(arg0, await to_candid_OtherProperty_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProperty(arg0: bigint, arg1: Property): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, await to_candid_Property_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, await to_candid_Property_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: ExternalBlob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Agent_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Promise<Agent> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_File_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _File): Promise<File> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_House_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _House): Promise<House> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_OtherProperty_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OtherProperty): Promise<OtherProperty> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Agent]): Promise<Agent | null> {
    return value.length === 0 ? null : await from_candid_Agent_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_File]): Promise<File | null> {
    return value.length === 0 ? null : await from_candid_File_n13(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_House]): Promise<House | null> {
    return value.length === 0 ? null : await from_candid_House_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OtherProperty]): Promise<OtherProperty | null> {
    return value.length === 0 ? null : await from_candid_OtherProperty_n26(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Property]): Promise<Property | null> {
    return value.length === 0 ? null : await from_candid_Property_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    citizenshipUpload: _File;
    workArea: string;
}): Promise<{
    contact: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    citizenshipUpload: File;
    workArea: string;
}> {
    return {
        contact: value.contact,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        address: value.address,
        citizenshipUpload: await from_candid_File_n13(_uploadFile, _downloadFile, value.citizenshipUpload),
        workArea: value.workArea
    };
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: _ExternalBlob;
    fileName: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): Promise<{
    id: bigint;
    content: ExternalBlob;
    fileName: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        content: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.content),
        fileName: value.fileName,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFloor: string;
    contact: string;
    ownerName: string;
    builtYear: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    naksaPass: string;
    price: string;
    totalLandArea: string;
    facing: string;
    location: string;
    attachments: Array<_File>;
    rooms: string;
}): Promise<{
    totalFloor: string;
    contact: string;
    ownerName: string;
    builtYear: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    naksaPass: string;
    price: string;
    totalLandArea: string;
    facing: string;
    location: string;
    attachments: Array<File>;
    rooms: string;
}> {
    return {
        totalFloor: value.totalFloor,
        contact: value.contact,
        ownerName: value.ownerName,
        builtYear: value.builtYear,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        notes: value.notes,
        naksaPass: value.naksaPass,
        price: value.price,
        totalLandArea: value.totalLandArea,
        facing: value.facing,
        location: value.location,
        attachments: await from_candid_vec_n24(_uploadFile, _downloadFile, value.attachments),
        rooms: value.rooms
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contact: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    category: string;
    price: string;
    location: string;
    attachments: Array<_File>;
}): Promise<{
    title: string;
    contact: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    category: string;
    price: string;
    location: string;
    attachments: Array<File>;
}> {
    return {
        title: value.title,
        contact: value.contact,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        notes: value.notes,
        category: value.category,
        price: value.price,
        location: value.location,
        attachments: await from_candid_vec_n24(_uploadFile, _downloadFile, value.attachments)
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationUrl: string;
    roadInfo: string;
    contact: string;
    ownerName: string;
    propertyType: string;
    nagarpalika: string;
    mukhSize: string;
    createdAt: bigint;
    createdBy: Principal;
    lambai: string;
    address: string;
    landArea: string;
    notes: string;
    price: string;
    facing: string;
    attachments: Array<_File>;
}): Promise<{
    locationUrl: string;
    roadInfo: string;
    contact: string;
    ownerName: string;
    propertyType: string;
    nagarpalika: string;
    mukhSize: string;
    createdAt: bigint;
    createdBy: Principal;
    lambai: string;
    address: string;
    landArea: string;
    notes: string;
    price: string;
    facing: string;
    attachments: Array<File>;
}> {
    return {
        locationUrl: value.locationUrl,
        roadInfo: value.roadInfo,
        contact: value.contact,
        ownerName: value.ownerName,
        propertyType: value.propertyType,
        nagarpalika: value.nagarpalika,
        mukhSize: value.mukhSize,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        lambai: value.lambai,
        address: value.address,
        landArea: value.landArea,
        notes: value.notes,
        price: value.price,
        facing: value.facing,
        attachments: await from_candid_vec_n24(_uploadFile, _downloadFile, value.attachments)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Promise<Array<Agent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Agent_n11(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_File>): Promise<Array<File>> {
    return await Promise.all(value.map(async (x)=>await from_candid_File_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n29(_uploadFile, _downloadFile, x)));
}
async function to_candid_Agent_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Agent): Promise<_Agent> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_File_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: File): Promise<_File> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function to_candid_House_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: House): Promise<_House> {
    return await to_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_OtherProperty_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OtherProperty): Promise<_OtherProperty> {
    return await to_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function to_candid_Property_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Property): Promise<_Property> {
    return await to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    citizenshipUpload: File;
    workArea: string;
}): Promise<{
    contact: string;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    address: string;
    citizenshipUpload: _File;
    workArea: string;
}> {
    return {
        contact: value.contact,
        name: value.name,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        address: value.address,
        citizenshipUpload: await to_candid_File_n34(_uploadFile, _downloadFile, value.citizenshipUpload),
        workArea: value.workArea
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: ExternalBlob;
    fileName: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): Promise<{
    id: bigint;
    content: _ExternalBlob;
    fileName: string;
    uploadedAt: bigint;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        content: await to_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value.content),
        fileName: value.fileName,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
async function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFloor: string;
    contact: string;
    ownerName: string;
    builtYear: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    naksaPass: string;
    price: string;
    totalLandArea: string;
    facing: string;
    location: string;
    attachments: Array<File>;
    rooms: string;
}): Promise<{
    totalFloor: string;
    contact: string;
    ownerName: string;
    builtYear: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    naksaPass: string;
    price: string;
    totalLandArea: string;
    facing: string;
    location: string;
    attachments: Array<_File>;
    rooms: string;
}> {
    return {
        totalFloor: value.totalFloor,
        contact: value.contact,
        ownerName: value.ownerName,
        builtYear: value.builtYear,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        notes: value.notes,
        naksaPass: value.naksaPass,
        price: value.price,
        totalLandArea: value.totalLandArea,
        facing: value.facing,
        location: value.location,
        attachments: await to_candid_vec_n39(_uploadFile, _downloadFile, value.attachments),
        rooms: value.rooms
    };
}
async function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contact: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    category: string;
    price: string;
    location: string;
    attachments: Array<File>;
}): Promise<{
    title: string;
    contact: string;
    createdAt: bigint;
    createdBy: Principal;
    notes: string;
    category: string;
    price: string;
    location: string;
    attachments: Array<_File>;
}> {
    return {
        title: value.title,
        contact: value.contact,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        notes: value.notes,
        category: value.category,
        price: value.price,
        location: value.location,
        attachments: await to_candid_vec_n39(_uploadFile, _downloadFile, value.attachments)
    };
}
async function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationUrl: string;
    roadInfo: string;
    contact: string;
    ownerName: string;
    propertyType: string;
    nagarpalika: string;
    mukhSize: string;
    createdAt: bigint;
    createdBy: Principal;
    lambai: string;
    address: string;
    landArea: string;
    notes: string;
    price: string;
    facing: string;
    attachments: Array<File>;
}): Promise<{
    locationUrl: string;
    roadInfo: string;
    contact: string;
    ownerName: string;
    propertyType: string;
    nagarpalika: string;
    mukhSize: string;
    createdAt: bigint;
    createdBy: Principal;
    lambai: string;
    address: string;
    landArea: string;
    notes: string;
    price: string;
    facing: string;
    attachments: Array<_File>;
}> {
    return {
        locationUrl: value.locationUrl,
        roadInfo: value.roadInfo,
        contact: value.contact,
        ownerName: value.ownerName,
        propertyType: value.propertyType,
        nagarpalika: value.nagarpalika,
        mukhSize: value.mukhSize,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        lambai: value.lambai,
        address: value.address,
        landArea: value.landArea,
        notes: value.notes,
        price: value.price,
        facing: value.facing,
        attachments: await to_candid_vec_n39(_uploadFile, _downloadFile, value.attachments)
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<File>): Promise<Array<_File>> {
    return await Promise.all(value.map(async (x)=>await to_candid_File_n34(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
